version: "3.8"

services:
  backend:
    build: .
    container_name: republica_facil_backend
    env_file:
      - .env
    ports: 
     - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://admin:admin@db:5432/db_republica_facil
    depends_on:
      - db
    volumes: 
     - .:/backend

  db:
    image: postgres
    container_name: republica_facil_db
    shm_size: 128mb
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128Mb
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db_republica_facil
    ports:
      - "5433:5432"
